name: upstanders
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_osm_plugin:
  #   path: 
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pin_code_fields: ^2.3.0+3
  custom_switch: ^0.0.1
  google_fonts: ^2.0.0
  pinput: ^1.2.0
  passcode_screen: ^2.0.0
  group_radio_button: ^1.0.1
  introduction_screen: ^2.1.0
  flutter_map: ^0.12.0
  google_maps_webservice:
  geolocator: ^7.0.3
  camera:
  permission_handler: ^8.1.4+2
  video_player: ^2.1.4
  better_player:
  scroll_to_index:
  shared_preferences: ^2.0.6
  # flutter_neumorphic: ^3.1.0
  audioplayers: ^0.19.1
  path_provider:
  http: ^0.13.3
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  uuid: ^3.0.4
  formz: ^0.4.0
  fluttertoast: ^8.0.7
  image_picker: ^0.8.1+1
  dio: ^4.0.0
  flutter_polyline_points: ^0.2.6
  google_maps_flutter: ^2.0.6
  persona_flutter: ^2.0.3
  # firebase_messaging: ^10.0.3
  # firebase_messaging: ^10.0.9
  flutter_local_notifications: ^8.1.1
  country_code_picker: ^2.0.2
  country_picker: ^2.0.7
  flutter_cache_manager: ^3.1.2
  flutter_image_compress: ^1.1.0
  background_locator: ^1.6.6
  location_permissions: ^4.0.0
  geocoding: ^2.0.0
  wakelock: 0.5.3+3
  flutter_sound: ^8.3.12
  intl: ^0.17.0
  audio_video_progress_bar: ^0.9.0
  lottie: ^1.2.0
  shimmer: ^2.0.0
  connectivity: ^3.0.6
  cached_network_image: ^3.1.0
  # flutter_socket_io: ^0.6.0
  flutter_chat_bubble: ^2.0.0
  socket_io_client: ^0.9.12
  socket_io: ^0.9.0+2
  # flutter_background_geolocation: ^4.3.0
  flutter_spinkit: ^5.1.0
  firebase_messaging: ^11.1.0
  gallery_saver: ^2.3.2
  image_cropper: ^1.4.1
  # flutter_downloader: ^1.7.1

  
  
    
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/users/
    - assets/animations/
    - assets/json/
    - assets/128/
    - assets/64/
    - assets/32/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
